site_name: ValtheraDB Docs
site_url: https://wxn0brp.github.io/ValtheraDB
repo_url: https://github.com/wxn0brP/ValtheraDB

theme:
  name: material
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
  logo: logo.svg
  favicon: logo.svg

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Core Concepts: core_concepts.md
  - API Reference:
      - Collection: collection.md
      - Valthera: valthera.md
      - Relation: relation.md
      - Search Options: search_opts.md
      - Find Options: find_opts.md
      - Updater: updater.md
      - Remote: remote.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
