site_name: ValtheraDB Docs
site_url: https://wxn0brp.github.io/ValtheraDB
repo_url: https://github.com/wxn0brP/ValtheraDB

theme:
  name: material
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
  logo: logo.svg
  favicon: logo.svg

nav:
  - Home: index.md
  - Relation: relation.md
  - Remote: remote.md
  - Updater: updater.md
  - Valthera: valthera.md
  - Find Options: find_opts.md
  - Search Options: search_opts.md
